/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;


/**
 *
 * @author osboxes
 */
public class Conection extends javax.swing.JFrame {

    /**
     * Creates new form Conection
     */
    private HelpConnect ayuda;
    private interData inClient;
    public Conection() {
        ayuda= new HelpConnect();
        inClient= new interData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextIP = new javax.swing.JTextField();
        TextPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnCnt = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OPHelp = new javax.swing.JMenuItem();
        OPBack = new javax.swing.JMenuItem();
        OPOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conectar con el servidor");
        setMinimumSize(new java.awt.Dimension(751, 396));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/osboxes/NetBeansProjects/SpiderBot/SpriderBot/iconoP1.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 12, 153, 150);

        jLabel2.setText("Realizar conexion con servidor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 350, 70);

        TextIP.setToolTipText("Ingrese la IP del servidor");
        getContentPane().add(TextIP);
        TextIP.setBounds(300, 150, 280, 35);

        TextPort.setToolTipText("Ingrese el puerto del servidor");
        getContentPane().add(TextPort);
        TextPort.setBounds(300, 210, 280, 35);

        jLabel3.setText("IP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 150, 66, 25);

        jLabel4.setText("Puerto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 220, 66, 25);

        BtnCnt.setText("Conectar");
        BtnCnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCntActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCnt);
        BtnCnt.setBounds(570, 280, 110, 37);
        getContentPane().add(ErrorLabel);
        ErrorLabel.setBounds(220, 90, 450, 0);

        jMenu1.setText("Options ");

        OPHelp.setText("Ayuda");
        OPHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPHelpActionPerformed(evt);
            }
        });
        jMenu1.add(OPHelp);

        OPBack.setText("Devolverse");
        OPBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPBackActionPerformed(evt);
            }
        });
        jMenu1.add(OPBack);

        OPOut.setText("Salir");
        OPOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPOutActionPerformed(evt);
            }
        });
        jMenu1.add(OPOut);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OPOutActionPerformed

    private void OPBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_OPBackActionPerformed

    private void OPHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPHelpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ayuda.setVisible(true);
    }//GEN-LAST:event_OPHelpActionPerformed

    private void BtnCntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCntActionPerformed
        // TODO add your handling code here:
        try{
            String ip= TextIP.getText();
            int puerto= Integer.parseInt(TextPort.getText());
            inClient.strartCliente(ip, puerto);
            if(!inClient.get_state())
                ErrorLabel.setText("Conexion exitosa");
        }catch(Exception e){
            e.printStackTrace();
            ErrorLabel.setText("error de conexion con servidor");
        }
        
    }//GEN-LAST:event_BtnCntActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCnt;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JMenuItem OPBack;
    private javax.swing.JMenuItem OPHelp;
    private javax.swing.JMenuItem OPOut;
    private javax.swing.JTextField TextIP;
    private javax.swing.JTextField TextPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
